/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "UnidialoguePDUs"
 * 	found in "../asn/UnidialoguePDUs.asn"
 */

#include <asn_internal.h>

#include "UniDialoguePDU.h"

static asn_TYPE_member_t asn_MBR_UniDialoguePDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UniDialoguePDU, choice.unidialoguePDU),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_AUDT_apdu,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unidialoguePDU"
		},
};
static asn_TYPE_tag2member_t asn_MAP_UniDialoguePDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 } /* unidialoguePDU at 13 */
};
static asn_CHOICE_specifics_t asn_SPC_UniDialoguePDU_specs_1 = {
	sizeof(struct UniDialoguePDU),
	offsetof(struct UniDialoguePDU, _asn_ctx),
	offsetof(struct UniDialoguePDU, present),
	sizeof(((struct UniDialoguePDU *)0)->present),
	asn_MAP_UniDialoguePDU_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UniDialoguePDU = {
	"UniDialoguePDU",
	"UniDialoguePDU",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_UniDialoguePDU_1,
	1,	/* Elements count */
	&asn_SPC_UniDialoguePDU_specs_1	/* Additional specs */
};

