/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 * 	found in "../asn/tcap.asn"
 */

#ifndef	_DialogueOC_H_
#define	_DialogueOC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DialogueOC */
typedef OCTET_STRING_t	 DialogueOC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DialogueOC;
asn_struct_free_f DialogueOC_free;
asn_struct_print_f DialogueOC_print;
asn_constr_check_f DialogueOC_constraint;
ber_type_decoder_f DialogueOC_decode_ber;
der_type_encoder_f DialogueOC_encode_der;
xer_type_decoder_f DialogueOC_decode_xer;
xer_type_encoder_f DialogueOC_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DialogueOC_H_ */
